### ISSUE TITLE
do poprawy

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Java-Script-10#1]
- [x] w tym zadaniu nie musisz tworzyc funkcji
- [x] zeby poprawnie wyswietlic tekst buttona przez `innerText` musisz jeszcze wskazac, ktory to button w tym miejscu: `newbutton.innerText`

**Comment by JoannaKu** [comment]
udało się :)

**Comment by michal-bootcamp** [comment]
brawo :)
